service: yt-summarizer

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-wsgi

custom:
  wsgi:
    app: main.app
    packRequirements: false